// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-Vkv8e6kEADjCvBzJ0Dx8ifbDL-dkRk',
    appId: '1:394156036263:web:7f0d0379181074bb974b82',
    messagingSenderId: '394156036263',
    projectId: 'shoppingapp-dcf3b',
    authDomain: 'shoppingapp-dcf3b.firebaseapp.com',
    storageBucket: 'shoppingapp-dcf3b.firebasestorage.app',
    measurementId: 'G-D6N6L0TFWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4dEhOkShmqAhk9fd0qOumcmwQXY697ks',
    appId: '1:394156036263:android:663c07fecfe5faf6974b82',
    messagingSenderId: '394156036263',
    projectId: 'shoppingapp-dcf3b',
    storageBucket: 'shoppingapp-dcf3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEc0brtcVdIlez7jt_tzF1aB2wiJE9V9M',
    appId: '1:394156036263:ios:368b1a51d14ecc32974b82',
    messagingSenderId: '394156036263',
    projectId: 'shoppingapp-dcf3b',
    storageBucket: 'shoppingapp-dcf3b.firebasestorage.app',
    androidClientId: '394156036263-1rm69dsk83f6g2herjf9a6p6k7iqvkl7.apps.googleusercontent.com',
    iosClientId: '394156036263-f6ivsi14nk4vl87a822p2a7ifn80c6us.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEc0brtcVdIlez7jt_tzF1aB2wiJE9V9M',
    appId: '1:394156036263:ios:368b1a51d14ecc32974b82',
    messagingSenderId: '394156036263',
    projectId: 'shoppingapp-dcf3b',
    storageBucket: 'shoppingapp-dcf3b.firebasestorage.app',
    androidClientId: '394156036263-1rm69dsk83f6g2herjf9a6p6k7iqvkl7.apps.googleusercontent.com',
    iosClientId: '394156036263-f6ivsi14nk4vl87a822p2a7ifn80c6us.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-Vkv8e6kEADjCvBzJ0Dx8ifbDL-dkRk',
    appId: '1:394156036263:web:a1e4c4cdbe0d241e974b82',
    messagingSenderId: '394156036263',
    projectId: 'shoppingapp-dcf3b',
    authDomain: 'shoppingapp-dcf3b.firebaseapp.com',
    storageBucket: 'shoppingapp-dcf3b.firebasestorage.app',
    measurementId: 'G-5BEX5RTJE5',
  );

}